# HTTP server configuration
quarkus:
  http:
    cors:
      enabled: true
      origins: "http://localhost:3000"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "Content-Type,Authorization"
  # Logging configuration
  log:
    category:
      "org.acme":
        level: INFO
      "io.quarkus":
        level: INFO

  datasource:
    db-kind: postgresql
    username: amazoff_user
    password: amazoff_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/amazoff_db
  hibernate-orm:
    database:
      generation: update
    dialect: org.hibernate.dialect.PostgreSQLDialect