# HTTP server configuration
quarkus:
  profile: dev
  http:
    cors:
      enabled: true
      origins: "http://localhost:3000"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "Content-Type,Authorization"
  # Logging configuration
  log:
    category:
      "org.acme":
        level: INFO
      "io.quarkus":
        level: INFO

  # Database configuration
  datasource:
    db-kind: h2
    username: sa
    password: sa
    jdbc:
      url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
      max-size: 16

  # Hibernate ORM configuration
  hibernate-orm:
    database:
      generation: drop-and-create
    dialect: org.hibernate.dialect.H2Dialect
    # sql-load-script: import.sql    

    # # Flyway configuration
    # flyway:
    #   migrate-at-start: true
    #   locations: db/migration

    # # Health check configuration
    # health:
    #   ui:
    #     enabled: true
    #     root-path: /health

    # # OpenAPI configuration
    # smallrye-openapi:
    #   path: /openapi
    #   info:
    #     title: "Microservice API"
    #     version: "1.0.0"

    # # Metrics configuration
    # metrics:
    #   enabled: true
    #   export:
    #     prometheus:
    #       enabled: true
    #       path: /metrics

  # # OIDC configuration
  # oidc:
  #   auth-server-url: https://auth.example.com
  #   client-id: my-microservice
  #   credentials:
  #     secret: my-secret
  #   token:
  #     issuer: https://auth.example.com
  #   application-type: service
  #   authentication:
  #     scopes:
  #       - openid
  #       - profile
  #       - email
