quarkus:
  datasource:
    db-kind: postgresql
    username: amazoff_user
    password: amazoff_password
    jdbc:
      url: jdbc:postgresql://localhost:5432/amazoff_db
  hibernate-orm:
    database:
      generation: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
